AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Lab - OTP Secret in Secrets Manager

Resources:

  IamOtpSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: iam-lab-otp-secret
      Description: One Time Password for IAM users in lab
      GenerateSecretString:
        SecretStringTemplate: '{"purpose": "iam-lab"}'
        GenerateStringKey: password
        PasswordLength: 12
        ExcludeCharacters: '"@/\'
        RequireEachIncludedType: true

Outputs:
  IamOtpSecretName:
    Description: Name of the OTP secret
    Value: !Ref IamOtpSecret